/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'publishDate' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
}
export type BookingStatus = string;
export interface ContentRecord {
  'key' : string,
  'value' : string,
  'updatedAt' : Timestamp,
}
export interface Inquiry {
  'id' : bigint,
  'inquiryType' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Photo {
  'id' : bigint,
  'url' : string,
  'thumbnailUrl' : [] | [string],
  'order' : bigint,
  'caption' : string,
  'mediaType' : string,
  'category' : PhotoCategory,
  'uploadedAt' : Timestamp,
}
export type PhotoCategory = string;
export interface PublicBookedDate { 'status' : BookingStatus, 'date' : string }
export interface PublicRoomStatus {
  'date' : string,
  'availableCount' : bigint,
  'isFullyBooked' : boolean,
}
export interface RoomAvailability {
  'date' : string,
  'bookedCount' : bigint,
  'availableCount' : bigint,
}
export interface RoomBooking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'remainingAmount' : bigint,
  'createdAt' : Timestamp,
  'numberOfRooms' : bigint,
  'checkInDate' : string,
  'totalAmount' : bigint,
  'notes' : string,
  'checkOutDate' : string,
  'aadhaarNumber' : string,
  'phoneNumber' : string,
  'paidAmount' : bigint,
}
export type Timestamp = bigint;
export interface VenueBooking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'remainingAmount' : bigint,
  'venueId' : VenueId,
  'date' : string,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'notes' : string,
  'aadhaarNumber' : string,
  'phoneNumber' : string,
  'paidAmount' : bigint,
}
export type VenueId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string, boolean], bigint>,
  'addPhoto' : ActorMethod<
    [PhotoCategory, string, string, string, [] | [string]],
    bigint
  >,
  'addRoomBooking' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      BookingStatus,
    ],
    bigint
  >,
  'addVenueBooking' : ActorMethod<
    [
      VenueId,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      BookingStatus,
    ],
    bigint
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deleteInquiry' : ActorMethod<[bigint], boolean>,
  'deletePhoto' : ActorMethod<[bigint], boolean>,
  'deleteRoomBooking' : ActorMethod<[bigint], boolean>,
  'deleteVenueBooking' : ActorMethod<[bigint], boolean>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllContentKeys' : ActorMethod<[], Array<string>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllRoomBookings' : ActorMethod<[], Array<RoomBooking>>,
  'getAllSiteContent' : ActorMethod<[], Array<ContentRecord>>,
  'getPhotosByCategory' : ActorMethod<[PhotoCategory], Array<Photo>>,
  'getPublicRoomStatus' : ActorMethod<[string], PublicRoomStatus>,
  'getRoomAvailability' : ActorMethod<[string], RoomAvailability>,
  'getSiteContent' : ActorMethod<[string], [] | [ContentRecord]>,
  'getVenueBookedDates' : ActorMethod<[VenueId], Array<PublicBookedDate>>,
  'getVenueBookings' : ActorMethod<[VenueId], Array<VenueBooking>>,
  'reorderGalleryMedia' : ActorMethod<[Array<bigint>], boolean>,
  'reorderPhoto' : ActorMethod<[bigint, bigint], boolean>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  'updateRoomBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      BookingStatus,
    ],
    boolean
  >,
  'updateSiteContent' : ActorMethod<[string, string], undefined>,
  'updateVenueBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      BookingStatus,
    ],
    boolean
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];