/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PhotoCategory = IDL.Text;
export const BookingStatus = IDL.Text;
export const VenueId = IDL.Text;
export const Timestamp = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'publishDate' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'inquiryType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const RoomBooking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'remainingAmount' : IDL.Nat,
  'createdAt' : Timestamp,
  'numberOfRooms' : IDL.Nat,
  'checkInDate' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Text,
  'checkOutDate' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'paidAmount' : IDL.Nat,
});
export const ContentRecord = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
  'category' : PhotoCategory,
  'uploadedAt' : Timestamp,
});
export const PublicRoomStatus = IDL.Record({
  'date' : IDL.Text,
  'availableCount' : IDL.Nat,
  'isFullyBooked' : IDL.Bool,
});
export const RoomAvailability = IDL.Record({
  'date' : IDL.Text,
  'bookedCount' : IDL.Nat,
  'availableCount' : IDL.Nat,
});
export const PublicBookedDate = IDL.Record({
  'status' : BookingStatus,
  'date' : IDL.Text,
});
export const VenueBooking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'remainingAmount' : IDL.Nat,
  'venueId' : VenueId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'paidAmount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addPhoto' : IDL.Func(
      [PhotoCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addRoomBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        BookingStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'addVenueBooking' : IDL.Func(
      [
        VenueId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        BookingStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRoomBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVenueBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllContentKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllRoomBookings' : IDL.Func([], [IDL.Vec(RoomBooking)], ['query']),
  'getAllSiteContent' : IDL.Func([], [IDL.Vec(ContentRecord)], ['query']),
  'getPhotosByCategory' : IDL.Func(
      [PhotoCategory],
      [IDL.Vec(Photo)],
      ['query'],
    ),
  'getPublicRoomStatus' : IDL.Func([IDL.Text], [PublicRoomStatus], ['query']),
  'getRoomAvailability' : IDL.Func([IDL.Text], [RoomAvailability], ['query']),
  'getSiteContent' : IDL.Func([IDL.Text], [IDL.Opt(ContentRecord)], ['query']),
  'getVenueBookedDates' : IDL.Func(
      [VenueId],
      [IDL.Vec(PublicBookedDate)],
      ['query'],
    ),
  'getVenueBookings' : IDL.Func([VenueId], [IDL.Vec(VenueBooking)], ['query']),
  'reorderGalleryMedia' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'reorderPhoto' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateRoomBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        BookingStatus,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSiteContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateVenueBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        BookingStatus,
      ],
      [IDL.Bool],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PhotoCategory = IDL.Text;
  const BookingStatus = IDL.Text;
  const VenueId = IDL.Text;
  const Timestamp = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'publishDate' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'inquiryType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RoomBooking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'remainingAmount' : IDL.Nat,
    'createdAt' : Timestamp,
    'numberOfRooms' : IDL.Nat,
    'checkInDate' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Text,
    'checkOutDate' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'paidAmount' : IDL.Nat,
  });
  const ContentRecord = IDL.Record({
    'key' : IDL.Text,
    'value' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
    'category' : PhotoCategory,
    'uploadedAt' : Timestamp,
  });
  const PublicRoomStatus = IDL.Record({
    'date' : IDL.Text,
    'availableCount' : IDL.Nat,
    'isFullyBooked' : IDL.Bool,
  });
  const RoomAvailability = IDL.Record({
    'date' : IDL.Text,
    'bookedCount' : IDL.Nat,
    'availableCount' : IDL.Nat,
  });
  const PublicBookedDate = IDL.Record({
    'status' : BookingStatus,
    'date' : IDL.Text,
  });
  const VenueBooking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'remainingAmount' : IDL.Nat,
    'venueId' : VenueId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'paidAmount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addPhoto' : IDL.Func(
        [PhotoCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addRoomBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          BookingStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'addVenueBooking' : IDL.Func(
        [
          VenueId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          BookingStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRoomBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVenueBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllContentKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllRoomBookings' : IDL.Func([], [IDL.Vec(RoomBooking)], ['query']),
    'getAllSiteContent' : IDL.Func([], [IDL.Vec(ContentRecord)], ['query']),
    'getPhotosByCategory' : IDL.Func(
        [PhotoCategory],
        [IDL.Vec(Photo)],
        ['query'],
      ),
    'getPublicRoomStatus' : IDL.Func([IDL.Text], [PublicRoomStatus], ['query']),
    'getRoomAvailability' : IDL.Func([IDL.Text], [RoomAvailability], ['query']),
    'getSiteContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentRecord)],
        ['query'],
      ),
    'getVenueBookedDates' : IDL.Func(
        [VenueId],
        [IDL.Vec(PublicBookedDate)],
        ['query'],
      ),
    'getVenueBookings' : IDL.Func(
        [VenueId],
        [IDL.Vec(VenueBooking)],
        ['query'],
      ),
    'reorderGalleryMedia' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'reorderPhoto' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateRoomBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          BookingStatus,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSiteContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateVenueBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          BookingStatus,
        ],
        [IDL.Bool],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };