/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RoomAvailability {
    date: string;
    bookedCount: bigint;
    availableCount: bigint;
}
export type Timestamp = bigint;
export interface ContentRecord {
    key: string;
    value: string;
    updatedAt: Timestamp;
}
export interface RoomBooking {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    remainingAmount: bigint;
    createdAt: Timestamp;
    numberOfRooms: bigint;
    checkInDate: string;
    totalAmount: bigint;
    notes: string;
    checkOutDate: string;
    aadhaarNumber: string;
    phoneNumber: string;
    paidAmount: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PublicRoomStatus {
    date: string;
    availableCount: bigint;
    isFullyBooked: boolean;
}
export interface PublicBookedDate {
    status: BookingStatus;
    date: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type BookingStatus = string;
export type PhotoCategory = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type VenueId = string;
export interface VenueBooking {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    remainingAmount: bigint;
    venueId: VenueId;
    date: string;
    createdAt: Timestamp;
    totalAmount: bigint;
    notes: string;
    aadhaarNumber: string;
    phoneNumber: string;
    paidAmount: bigint;
}
export interface Announcement {
    id: bigint;
    title: string;
    publishDate: string;
    body: string;
    createdAt: Timestamp;
    isActive: boolean;
}
export interface Inquiry {
    id: bigint;
    inquiryType: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
    phone: string;
}
export interface Photo {
    id: bigint;
    url: string;
    thumbnailUrl?: string;
    order: bigint;
    caption: string;
    mediaType: string;
    category: PhotoCategory;
    uploadedAt: Timestamp;
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addAnnouncement(title: string, body: string, publishDate: string, isActive: boolean): Promise<bigint>;
    addPhoto(category: PhotoCategory, url: string, caption: string, mediaType: string, thumbnailUrl: string | null): Promise<bigint>;
    addRoomBooking(checkInDate: string, checkOutDate: string, numberOfRooms: bigint, customerName: string, phoneNumber: string, aadhaarNumber: string, totalAmount: bigint, paidAmount: bigint, remainingAmount: bigint, notes: string, bookingStatus: BookingStatus): Promise<bigint>;
    addVenueBooking(venueId: VenueId, date: string, customerName: string, phoneNumber: string, aadhaarNumber: string, totalAmount: bigint, paidAmount: bigint, remainingAmount: bigint, notes: string, bookingStatus: BookingStatus): Promise<bigint>;
    deleteAnnouncement(id: bigint): Promise<boolean>;
    deleteInquiry(id: bigint): Promise<boolean>;
    deletePhoto(id: bigint): Promise<boolean>;
    deleteRoomBooking(id: bigint): Promise<boolean>;
    deleteVenueBooking(id: bigint): Promise<boolean>;
    getActiveAnnouncements(): Promise<Array<Announcement>>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllContentKeys(): Promise<Array<string>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllRoomBookings(): Promise<Array<RoomBooking>>;
    getAllSiteContent(): Promise<Array<ContentRecord>>;
    getPhotosByCategory(category: PhotoCategory): Promise<Array<Photo>>;
    getPublicRoomStatus(date: string): Promise<PublicRoomStatus>;
    getRoomAvailability(date: string): Promise<RoomAvailability>;
    getSiteContent(key: string): Promise<ContentRecord | null>;
    getVenueBookedDates(venueId: VenueId): Promise<Array<PublicBookedDate>>;
    getVenueBookings(venueId: VenueId): Promise<Array<VenueBooking>>;
    reorderGalleryMedia(orderedIds: Array<bigint>): Promise<boolean>;
    reorderPhoto(id: bigint, newOrder: bigint): Promise<boolean>;
    submitInquiry(name: string, phone: string, email: string, inquiryType: string, message: string): Promise<bigint>;
    updateAnnouncement(id: bigint, title: string, body: string, publishDate: string, isActive: boolean): Promise<boolean>;
    updateRoomBooking(id: bigint, checkInDate: string, checkOutDate: string, numberOfRooms: bigint, customerName: string, phoneNumber: string, aadhaarNumber: string, totalAmount: bigint, paidAmount: bigint, remainingAmount: bigint, notes: string, bookingStatus: BookingStatus): Promise<boolean>;
    updateSiteContent(key: string, value: string): Promise<void>;
    updateVenueBooking(id: bigint, customerName: string, phoneNumber: string, aadhaarNumber: string, totalAmount: bigint, paidAmount: bigint, remainingAmount: bigint, notes: string, bookingStatus: BookingStatus): Promise<boolean>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { ContentRecord as _ContentRecord, Photo as _Photo, PhotoCategory as _PhotoCategory, Timestamp as _Timestamp, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPhoto(arg0: PhotoCategory, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addRoomBooking(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string, arg10: BookingStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async addVenueBooking(arg0: VenueId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string, arg9: BookingStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVenueBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVenueBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteInquiry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteRoomBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoomBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoomBooking(arg0);
            return result;
        }
    }
    async deleteVenueBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVenueBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVenueBooking(arg0);
            return result;
        }
    }
    async getActiveAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncements();
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllContentKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentKeys();
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllRoomBookings(): Promise<Array<RoomBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomBookings();
            return result;
        }
    }
    async getAllSiteContent(): Promise<Array<ContentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSiteContent();
            return result;
        }
    }
    async getPhotosByCategory(arg0: PhotoCategory): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByCategory(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByCategory(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicRoomStatus(arg0: string): Promise<PublicRoomStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicRoomStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicRoomStatus(arg0);
            return result;
        }
    }
    async getRoomAvailability(arg0: string): Promise<RoomAvailability> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomAvailability(arg0);
            return result;
        }
    }
    async getSiteContent(arg0: string): Promise<ContentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVenueBookedDates(arg0: VenueId): Promise<Array<PublicBookedDate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVenueBookedDates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVenueBookedDates(arg0);
            return result;
        }
    }
    async getVenueBookings(arg0: VenueId): Promise<Array<VenueBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVenueBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVenueBookings(arg0);
            return result;
        }
    }
    async reorderGalleryMedia(arg0: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderGalleryMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderGalleryMedia(arg0);
            return result;
        }
    }
    async reorderPhoto(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderPhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderPhoto(arg0, arg1);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateAnnouncement(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateRoomBooking(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: bigint, arg9: bigint, arg10: string, arg11: BookingStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async updateSiteContent(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(arg0, arg1);
            return result;
        }
    }
    async updateVenueBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: string, arg8: BookingStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVenueBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVenueBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_Photo_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Photo {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentRecord]): ContentRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    thumbnailUrl: [] | [string];
    order: bigint;
    caption: string;
    mediaType: string;
    category: _PhotoCategory;
    uploadedAt: _Timestamp;
}): {
    id: bigint;
    url: string;
    thumbnailUrl?: string;
    order: bigint;
    caption: string;
    mediaType: string;
    category: PhotoCategory;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        url: value.url,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.thumbnailUrl)),
        order: value.order,
        caption: value.caption,
        mediaType: value.mediaType,
        category: value.category,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Array<Photo> {
    return value.map((x)=>from_candid_Photo_n10(_uploadFile, _downloadFile, x));
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
